package br.com.meetingfaces.view;

import javax.swing.table.DefaultTableModel;
import br.com.meetingfaces.dao.DescricaoDAO;
import br.com.meetingfaces.ctr.DescricaoCTR;
import java.sql.ResultSet;

/**
 *
 * @author vitor
 */
public class DescricaoVIEW extends javax.swing.JInternalFrame {

    DescricaoDAO descricaoDAO = new DescricaoDAO();
    DescricaoCTR descricaoCTR = new DescricaoCTR();

    ResultSet rs;
    DefaultTableModel modelo_consulta_m;

    /**
     * Creates new form DescricaoVIEW
     */
    public DescricaoVIEW() {
        initComponents();

        modelo_consulta_m = (DefaultTableModel) tabelaDesc.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDesc = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        tabelaDesc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Descrição", "Nome do morador", "Nome do usuário que realizou a operação"
            }
        ));
        tabelaDesc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaDescMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaDesc);

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jButton1)
                .addGap(43, 43, 43)
                .addComponent(jButton2)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaDescMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaDescMouseClicked

    }//GEN-LAST:event_tabelaDescMouseClicked

    private void preencheTabela() {
        try {
            //Limpa todas as linhas
            modelo_consulta_m.setNumRows(0);

            rs = descricaoCTR.consultarDesc(); //1 = é a pesquisa por nome na classe DAO
            while (rs.next()) {
                modelo_consulta_m.addRow(new Object[]{
                    rs.getString("descricao"),
                    rs.getString("primeiro_nome_usuario"),
                    rs.getString("primeiro_nome_morador"),});
            }
        } catch (Exception erTab) {
            System.out.println("Erro SQL: " + erTab);
        }
    }//Fecha método preencheTabela

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaDesc;
    // End of variables declaration//GEN-END:variables
}
