package br.com.meetingfaces.view;

import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import br.com.meetingfaces.ctr.AdministradorCTR;
import br.com.meetingfaces.dto.AdministradorDTO;

public class SelectAdminVIEW extends javax.swing.JFrame {

    AdministradorDTO administradorDTO = new AdministradorDTO();
    AdministradorCTR administradorCTR = new AdministradorCTR();
    DefaultTableModel modelo_tabela_admin;
    ResultSet rs;

    /**
     * Creates new form SelectAdminVIEW
     */
    public SelectAdminVIEW() {
        initComponents();

        modelo_tabela_admin = (DefaultTableModel) Tabela_Admin.getModel();
        preencheTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela_Admin = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tabela_Admin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "iD", "Primeiro nome", "Segundo nome", "Email"
            }
        ));
        Tabela_Admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabela_AdminMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela_Admin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tabela_AdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabela_AdminMouseClicked
//        selectDesc(Integer.parseInt(String.valueOf(Tabela_Admin.getValueAt(Tabela_Admin.getSelectedRow(), 0))));
    }//GEN-LAST:event_Tabela_AdminMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectAdminVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectAdminVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectAdminVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectAdminVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectAdminVIEW().setVisible(true);
            }
        });
    }

    private void preencheTabela() {
        try {
            //Limpa todas as linhas
            modelo_tabela_admin.setNumRows(0);

            //Enquanto tiver linhas - faça
            rs = administradorCTR.consultarAdmin(administradorDTO, 3);
            //1 = é a pesquisa por nome na classe DAO
            while (rs.next()) {
                modelo_tabela_admin.addRow(new Object[]{
                    rs.getInt("ID_ADMINISTRADOR"),
                    rs.getString("PRIMEIRO_NOME"),
                    rs.getString("SEGUNDO_NOME"),
                    rs.getString("EMAIL")});
            }
        } catch (Exception erTab) {
            System.out.println("Erro SQL: " + erTab);
        }
    }//Fecha método preencheTabela

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela_Admin;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
