/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.meetingfaces.view;

import br.com.meetingfaces.dto.AdministradorDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author vitor
 */
public class TelaInicalVIEW extends javax.swing.JFrame {

    AdministradorDTO administradorDTO = new AdministradorDTO();
    int id_login;

    /**
     * Creates new form TelaInicalVIEW
     */
    public TelaInicalVIEW(int id_login) {
        initComponents();
        this.id_login = id_login;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crudMorador = new javax.swing.JButton();
        aprovDesc = new javax.swing.JButton();
        listAdm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        sairBotao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        crudMorador.setText("Cadastrar/editar/excluir moradores de rua");
        crudMorador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crudMoradorActionPerformed(evt);
            }
        });

        aprovDesc.setText("Aprovação de descrições");
        aprovDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aprovDescActionPerformed(evt);
            }
        });

        listAdm.setText("Listagem de administradores");
        listAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listAdmActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleciona qual operação deseja realizar");

        sairBotao.setText("Sair");
        sairBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listAdm)
                    .addComponent(sairBotao)
                    .addComponent(aprovDesc)
                    .addComponent(crudMorador)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(306, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(crudMorador)
                .addGap(35, 35, 35)
                .addComponent(listAdm)
                .addGap(43, 43, 43)
                .addComponent(aprovDesc)
                .addGap(41, 41, 41)
                .addComponent(sairBotao)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crudMoradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crudMoradorActionPerformed
        this.dispose();
        CadastroMoradorVIEW cadMorVIEW = new CadastroMoradorVIEW(id_login);
        cadMorVIEW.setVisible(true);
    }//GEN-LAST:event_crudMoradorActionPerformed

    private void aprovDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aprovDescActionPerformed
        this.dispose();
        DescricaoVIEW descricaoVIEW = new DescricaoVIEW();

        descricaoVIEW.setVisible(true);
    }//GEN-LAST:event_aprovDescActionPerformed

    private void listAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listAdmActionPerformed
        this.dispose();
        SelectAdminVIEW selectAdminVIEW = new SelectAdminVIEW();
        selectAdminVIEW.setVisible(true);
    }//GEN-LAST:event_listAdmActionPerformed

    private void sairBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairBotaoActionPerformed
        sair();
    }//GEN-LAST:event_sairBotaoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaInicalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaInicalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaInicalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaInicalVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaInicalVIEW().setVisible(true);
//            }
//        });
//    }
    private void sair() {
        Object[] options = {"Sair", "Cancelar"};
        if (JOptionPane.showOptionDialog(null, "Deseja Sair do Sistema", "Informação",
                JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]) == 0) {
            System.exit(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aprovDesc;
    private javax.swing.JButton crudMorador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton listAdm;
    private javax.swing.JButton sairBotao;
    // End of variables declaration//GEN-END:variables
}
