CREATE TABLE USUARIO(
	ID_USUARIO SERIAL,
	PRIMEIRO_NOME varchar(20),
	SEGUNDO_NOME varchar(20),
	TELEFONE varchar(15),
	DATA_NASC date,
	EMAIL varchar(90),
	SENHA varchar(255), 
	CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO),
	CONSTRAINT uniquekey_usuario_email UNIQUE (email)
);

CREATE TABLE ADMINISTRADOR(
	ID_ADMINISTRADOR SERIAL,
	PRIMEIRO_NOME VARCHAR(20),
	SEGUNDO_NOME VARCHAR(20),
	EMAIL VARCHAR(100),
	SENHA VARCHAR(255),
	CONSTRAINT PK_ADMINISTRADOR PRIMARY KEY (ID_ADMINISTRADOR),
	CONSTRAINT UNIQUEKEY_ADM_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE morador(
	id_morador SERIAL,
	primeiro_nome varchar(45),
	segundo_nome varchar(45),
	cidade_atual varchar(30),
	cidade_natal varchar(30),
	data_nasc varchar(10),
	nome_familiar_proximo varchar(50),
	grau_parentesco varchar(40),
	ID_ADMINISTRADOR int not null,
	CONSTRAINT PK_MORADOR PRIMARY KEY (ID_MORADOR),
	
	CONSTRAINT fk_ADM_morador FOREIGN KEY (ID_ADMINISTRADOR)
		REFERENCES ADMINISTRADOR(ID_ADMINISTRADOR)
);

CREATE TABLE DESCRICAO(
	ID_DESCRICAO SERIAL,
	ID_USUARIO int not null,
	ID_MORADOR int not null,
	COMENTARIO varchar(255),
	SITUACAO varchar(20),
	CONSTRAINT PK_DESCRICAO PRIMARY KEY (ID_DESCRICAO),
	
	CONSTRAINT fk_usuario_descricao FOREIGN KEY (id_usuario)
		REFERENCES usuario(id_usuario),
	
	CONSTRAINT fk_descricao_morador FOREIGN KEY (id_morador)
		REFERENCES morador(id_morador)
);	